name: Docker Build and Push

on:
  push:
    branches:
      - '*'
    tags:
      - '**'
  pull_request:
    branches:
      - '*'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: ethpandaops/ethereum-genesis-generator

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ARM]  # Change self-hosted-arm to your ARM runner's label
        platform: ['linux/amd64', 'linux/arm64']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: ${{ matrix.platform }}
        tags: |
          ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          ${{ env.IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }}
          ${{ env.IMAGE_NAME }}:${{ github.ref_name }}-${{ matrix.platform }}
          ${{ env.IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }}-${{ matrix.platform }}
